spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/springdb
    username: marisak
    password: reimu98
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
  security:
    jwt:
      secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
      expiration: 86400000

  application:
    name: javierdiez
#Google auth

